#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-

def bake_last_windows_updates(opsys, conf, conf_dir, plugins_dir):
    if conf:
        shutil.copy2(cmk.paths.local_agents_dir + "/plugins/last_windows_updates.vbs",
                     plugins_dir + "/last_windows_updates.vbs")

bakery_info["last_windows_updates"] = {
"bake_function" : bake_last_windows_updates,
"os"            : [ "windows", ],
}
