#!/usr/bin/env python
# -*- encoding: utf-8; py-indent-offset: 4 -*-

def bake_wsus_sync_status(opsys, conf, conf_dir, plugins_dir):
    if conf[0] == "activate":
        shutil.copy2(cmk.paths.local_agents_dir  + "/plugins/wsus_sync_status.ps1",
                     plugins_dir + "/wsus_sync_status.ps1")

    #if conf == True:
    #    conf = {}

        def write_wsus_sync_status_ini(path, port):
            f = file(path, "w")
            f.write("#define wsus port\n\n")
            f.write("[connection]\n")
            if port:
                f.write("port = %s\n" % port)


        write_wsus_sync_status_ini(conf_dir + "/wsus_sync_status.ini", conf[1])

bakery_info["wsus_sync_status"] = {
    "bake_function" : bake_wsus_sync_status,
    "os"            : [ "windows" ],
}

