#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-
# +------------------------------------------------------------------+
# |             ____ _               _        __  __ _  __           |
# |            / ___| |__   ___  ___| | __   |  \/  | |/ /           |
# |           | |   | '_ \ / _ \/ __| |/ /   | |\/| | ' /            |
# |           | |___| | | |  __/ (__|   <    | |  | | . \            |
# |            \____|_| |_|\___|\___|_|\_\___|_|  |_|_|\_\           |
# |                                                                  |
# | Copyright Mathias Kettner 2014             mk@mathias-kettner.de |
# +------------------------------------------------------------------+
#
# This file is part of Check_MK.
# The official homepage is at http://mathias-kettner.de/check_mk.
#
# check_mk is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  check_mk is  distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# tails. You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.

#<<<check_bi>>>
#Aggr1|Aggregation state is OK|0
#Aggr2|Aggregation state is OK|0
#Aggr3|Aggregation state is OK|0

def inventory_check_bi(info):
    for line in info:
        yield ' '.join(line[0:line.index('Aggregation')]), {}

def check_check_bi(item, params, info):
    for line in info:
        if ' '.join(line[0:line.index('Aggregation')]) == item:
            if len(line[line.index('Aggregation'):]) == 5:
                 infotext = ' '.join(line[-5:-1])
            elif len(line[line.index('Aggregation'):]) == 7:
                 infotext = ' '.join(line[-7:-1])
            else:
                 infotext = ' '.join(line[-8:-1])
            if line[-1] == "0":
                state = 0
            elif line[-1] == '1':
                state = 1
            elif line[-1] == '2':
                state = 2
            else:
                state = 3
    yield state, infotext

check_info['check_bi'] = {
    "check_function"          : check_check_bi,
    "inventory_function"      : inventory_check_bi,
    "service_description"     : "%s",
    "group"                   : "check_bi",
}
