#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-

def inventory_last_windows_updates(info):
    if info:
        return [ ( "Last Windows Updates", None ) ]

def check_last_windows_updates(item, no_params, info):
    state = 0
    if "Registry" not in info[0][0]:
        date_x = info[0][0].split("-")
        date = "%s-%s-%s" % (date_x[0], date_x[1], date_x[2])

        infotext = "Updates last installed on %s \n %s" % (date, date)
    else:
        infotext = "Registry Key not found"
    
    yield state, infotext
                
        


check_info["last_windows_updates"] = {
    'check_function':          check_last_windows_updates,
    'inventory_function':      inventory_last_windows_updates,
    'service_description':     '%s',
    'group':                   'last_windows_updates',
    'has_perfdata':            True,
}
