multisite_builtin_views.update({
    'hostdowntimes_by_author': {'browser_reload': 30,
                                'owner': '',
                                'column_headers': 'pergroup',
                                'context': {'host_scheduled_downtime_depth': {'is_host_scheduled_downtime_depth': '1'},
                                            'service_scheduled_downtime_depth': {'is_service_scheduled_downtime_depth': '0'}},
                                'datasource': 'downtimes',
                                'description': u'',
                                'force_checkboxes': False,
                                'group_painters': [],
                                'hidden': True,
                                'hidebutton': True,
                                'icon': None,
                                'layout': 'table',
                                'linktitle': u'Host Downtimes',
                                'mobile': False,
                                'mustsearch': False,
                                'name': 'hostdowntimes_by_author',
                                'num_columns': 1,
                                'painters': [('host_state', None, None),
                                             ('host', 'hoststatus', None),
                                             ('downtime_start_time', None, None),
                                             ('downtime_end_time', None, None),
                                             ('downtime_author', None, None),
                                             ('downtime_comment', None, None)],
                                'play_sounds': False,
                                'public': True,
                                'single_infos': [],
                                'sorters': [('downtime_start_time', True),
                                            ('site_host', False)],
                                'title': u'Current host downtimes',
                                'topic': u'Test',
                                'user_sortable': True}})
