multisite_builtin_views.update({
    'hostproblems_ack_by_author': {'browser_reload': 30,
                                   'column_headers': 'pergroup',
                                   'context': {'comment': {'comment_author': ''},
                                               'host_acknowledged': {'is_host_acknowledged': '1'},
                                               'host_scheduled_downtime_depth': {'is_host_scheduled_downtime_depth': '0'},
                                               'hoststate': {'hst0': '',
                                                             'hst1': 'on',
                                                             'hst2': 'on',
                                                             'hstp': 'on'},
                                               'service_acknowledged': {'is_service_acknowledged': '0'}},
                                               'datasource': 'comments',
                                   'description': u'',
                                   'force_checkboxes': False,
                                   'group_painters': [('comment_author_alias', '', None)],
                                   'hidden': True,
                                   'hidebutton': True,
                                   'icon': None,
                                   'layout': 'table',
                                   'linktitle': u'Acknowledged Host Problems by author',
                                   'mobile': False,
                                   'mustsearch': False,
                                   'name': 'hostproblems_ack_by_author',
                                   'num_columns': 1,
                                   'owner': '',
                                   'painters': [('host_state', None, None),
                                                ('host', 'hoststatus', None),
                                                ('host_plugin_output', None, None),
                                                ('host_comments', None, None),
                                                ('host_state_age', None, None)],
                                   'play_sounds': False,
                                   'public': True,
                                   'single_infos': [],
                                   'sorters': [('comment_author_alias', False),
                                               ('hoststate', True),
                                               ('host_state_age', True),
                                               ('site_host', False)],
                                   'title': u'Acknowledged Host Problems by author',
                                   'topic': u'Hosts',
                                   'user_sortable': True}})
